layout_spectrum: 0.008960574
typography_spectrum: 0.6594982
color:
  saturation: 1
  lightness: 0.7007169
  brandStrength: 0.7939068
  brandColors:
    - '#EFE8DE'
    - '#283521'
    - '#96CB7D'
    - '#577048'
    - '#859763'
  rhythmicContrast: 0.2222222
name: AYANA CONCEPTS
